# Site settings

title: OSÂ²Product
email: youremailaddress@gmail.com
description: The Jekyll version of the Spectral theme by HTML5 UP.
# baseurl: ""
# url: "http://localhost:4000"

# Uncomment the lines below if you are deploying to GitHub Pages
baseurl: "/spectral-jekyll-theme" 
url: "https://janhalen.github.io" 

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

defaults:
  - scope:
      path: "content"
      type: "pages"
    values:
      permalink: /

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url:
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
